### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by 7thghoul** [ChrisMichaelPerezSantiago/gogoanime#1]
gogo.search(query)
        .then(data => {
            console.log(data)

(node:8768) UnhandledPromiseRejectionWarning: FetchError: request to https://www10.gogoanime.io/search.html?keyword=clannad failed, reason: read ECONNRESET

**Comment by ChrisMichaelPerezSantiago** [comment]
Hello @7thghoul,

Unfortunately I am no longer maintaining the library.

**Comment by 7thghoul** [comment]
The website is still active, there's a minor change in the website's code. You can do it!

**Comment by ChrisMichaelPerezSantiago** [comment]
@7thghoul ,

Unfortunately I am no longer maintaining any of the APIs that I have implemented related to anime.

Sorry for the inconvenience!

**Comment by 7thghoul** [comment]
Then can you explain me how do i fix that issue? I'll keep your legacy alive.
