### ISSUE TITLE
Null episodes when ep list is exactaly at 500

### ISSUE THREAD

**Issue by Subu19** [ChrisMichaelPerezSantiago/gogoanime#5]
**Description**
i was fetching data for NARUTO SHIPPUDEN and it returned null episodes.

**When it happens?**
if an anime has total number of episodes 100/200/300 and so on

**Why it happens?**
After knowing this bug, i looked into package and found something in app.js
animeContentHandler was splitting  "-" from episode list but there wont be any  "-" if the anime has total episodes of 100/200/300

**How i fixed it**
![image](https://user-images.githubusercontent.com/59548115/116644478-33d7cf00-a993-11eb-851a-8d86605de581.png)

i fixed it but its a npm package so it will return back to default code when "npm install"

**Please fix this package soon.**

**Comment by ChrisMichaelPerezSantiago** [comment]
@Subu19 I have merged your correction, and I have updated the pkg to v1.0.2

Thank you for your contribution!
